import { assembleReference, assembleSkill, assembleSkillIndex } from '../core/template-engine.js';
import type { AgentDefinition, AigentTeamConfig, CompiledOutput } from '../core/types.js';

/**
 * Cursor IDE marketplace plugin layout (see https://cursor.com/docs/plugins
 * and https://cursor.com/docs/reference/plugins.md).
 * Output root is the folder you can symlink to ~/.cursor/plugins/local/<name>.
 */

function formatFrontmatter(data: Record<string, unknown>): string {
  const lines: string[] = ['---'];
  for (const [key, value] of Object.entries(data)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      lines.push(`${key}:`);
      for (const item of value) {
        lines.push(`  - ${item}`);
      }
    } else {
      lines.push(`${key}: ${JSON.stringify(value)}`);
    }
  }
  lines.push('---');
  return lines.join('\n');
}

/** Cursor plugin `name`: lowercase kebab-case, alphanumerics + hyphens + periods */
export function toKebabCursorPluginId(projectName: string): string {
  const s = projectName
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/\.{2,}/g, '.');
  if (!s || !/^[a-z0-9]/.test(s)) {
    return `aigent-team-${s || 'pack'}`.replace(/^-+/, '');
  }
  return s;
}

export function compileCursorIdePlugin(
  agents: AgentDefinition[],
  config: AigentTeamConfig,
  rootDir: string,
): CompiledOutput[] {
  const outputs: CompiledOutput[] = [];
  const pluginId = toKebabCursorPluginId(config.projectName);
  const firstLine = (text: string) => text.trim().split('\n')[0] ?? '';

  outputs.push({
    filePath: `${rootDir}/.cursor-plugin/plugin.json`,
    content:
      JSON.stringify(
        {
          name: pluginId,
          version: '0.1.0',
          description: `Agent team pack for ${config.projectName} (generated by aigent-team)`,
          keywords: ['aigent-team', 'agents'],
          author: { name: 'aigent-team' },
        },
        null,
        2,
      ) + '\n',
    overwriteStrategy: 'replace',
  });

  const sharedKnowledge = agents
    .flatMap((a) => a.sharedKnowledge)
    .filter((v, i, arr) => arr.indexOf(v) === i && v)
    .join('\n\n---\n\n');

  if (sharedKnowledge) {
    const frontmatter = formatFrontmatter({
      description: 'Shared project conventions and knowledge for all team agents',
      alwaysApply: true,
    });
    outputs.push({
      filePath: `${rootDir}/rules/shared-conventions.mdc`,
      content: `${frontmatter}\n\n${sharedKnowledge}\n`,
      overwriteStrategy: 'replace',
    });
  }

  for (const agent of agents) {
    const globs = agent.globs?.length ? agent.globs.join(', ') : undefined;
    const frontmatterData: Record<string, unknown> = {
      description: firstLine(agent.description),
      alwaysApply: !globs,
    };
    if (globs) {
      frontmatterData.globs = globs;
    }
    const frontmatter = formatFrontmatter(frontmatterData);
    const body = assembleSkillIndex(agent);
    outputs.push({
      filePath: `${rootDir}/rules/${agent.id}-agent.mdc`,
      content: `${frontmatter}\n\n${body}\n`,
      overwriteStrategy: 'replace',
    });
  }

  for (const agent of agents) {
    if (!agent.references?.length) continue;
    const globs = agent.globs?.length ? agent.globs.join(', ') : undefined;
    for (const ref of agent.references) {
      const refFrontmatter = formatFrontmatter({
        description: `${agent.name} reference: ${ref.title}`,
        alwaysApply: false,
        globs: globs || undefined,
      });
      outputs.push({
        filePath: `${rootDir}/rules/${agent.id}-refs/${ref.id}.mdc`,
        content: `${refFrontmatter}\n\n${assembleReference(ref)}\n`,
        overwriteStrategy: 'replace',
      });
    }
  }

  for (const agent of agents) {
    if (!agent.skills?.length) continue;
    for (const skill of agent.skills) {
      const skillId = `${agent.id}-${skill.id}`;
      const descSource =
        skill.description?.trim() || skill.name?.trim() || skill.trigger?.trim() || `Procedure for ${agent.name}`;
      const skillFrontmatter = formatFrontmatter({
        name: skillId,
        description: firstLine(descSource),
      });
      outputs.push({
        filePath: `${rootDir}/skills/${skillId}/SKILL.md`,
        content: `${skillFrontmatter}\n\n${assembleSkill(skill)}\n`,
        overwriteStrategy: 'replace',
      });
    }
  }

  return outputs;
}
